version: "3.9"

services:

  # ============================================================
  # 🔥 NGINX - LOAD BALANCER
  # ============================================================
  load-balancer:
    image: nginx:alpine
    container_name: rinha_nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "30M"

  # ============================================================
  # 🐘 POSTGRES
  # ============================================================
  db:
    image: postgres:16-alpine
    container_name: postgres_rinha
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    networks:
      - rinha-net
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=25MB
      -c synchronous_commit=off
      -c full_page_writes=off
      -c wal_buffers=4MB
      -c effective_cache_size=50MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "200M"

  # ============================================================
  # ⚡ KAFKA (KRaft)
  # ============================================================
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092" # Abre a porta para o seu Windows/Linux
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # LISTENERS: Interno (9093) e Externo (9092)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # ADVERTISED: Como a sua IDE vai achar o Kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - rinha-net

  # ============================================================
  # 📊 KAFKA UI
  # ============================================================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080" # Se a porta 8080 estiver ocupada pela sua API, use "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: rinha-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092 # Nome do serviço no docker
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - rinha-net
  # ============================================================
  # Dozzle (Visualizador de Logs em Tempo Real)
  # ============================================================
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rinha-net
  # ============================================================
  # 🚀 APIs
  # ============================================================
  api01: &api_config
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rinha
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JAVA_TOOL_OPTIONS: "-Xms64M -Xmx64M -XX:+UseSerialGC"
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"

  api02:
    <<: *api_config

networks:
  rinha-net:
    driver: bridge

