spring.datasource.url=jdbc:postgresql://localhost:5432/rinha
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Kafka Local
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=rinha-local