spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://db:5432/rinha
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 10000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never # 🔥 importante pra não rodar script em prod

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    consumer:
      group-id: rinha-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 50

    listener:
      ack-mode: manual
      missing-topics-fatal: false

    producer:
      acks: 1
      retries: 3
      batch-size: 16384
      linger-ms: 5

server:
  port: 8080
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.springframework.kafka: WARN
    org.hibernate.SQL: WARN